apiVersion: v1
kind: Service
metadata:
  name: {{ include "mox.fullname" . }}-internal
  labels:
    {{- include "mox.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "mox.selectorLabels" . | nindent 4 }}
  ports:
    {{- if .Values.listeners.metrics.enabled }}
    - name: metrics
      port: {{ .Values.listeners.metrics.port }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
